spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: incident
          uri: http://localhost:8081
          predicates:
            - Path=/v1/incidents/**
          filters:
            - GatewayGlobalFilter
